-- Property Listings API: schema.
-- Identifiers are UUIDs generated by the database (gen_random_uuid, built into Postgres 13+) so
-- nothing can be enumerated by counting.

create or replace function set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table agencies (
  id           uuid primary key default gen_random_uuid(),
  name         text not null check (length(trim(name)) > 0),
  city         text not null,
  state        text not null,
  phone        text not null,
  email        text not null,
  founded_year integer not null check (founded_year between 1950 and 2100),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table agents (
  id               uuid primary key default gen_random_uuid(),
  agency_id        uuid not null references agencies(id) on delete restrict,
  full_name        text not null check (length(trim(full_name)) > 0),
  email            text not null unique,
  phone            text not null,
  years_experience integer not null check (years_experience >= 0),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table listings (
  id            uuid primary key default gen_random_uuid(),
  agent_id      uuid not null references agents(id) on delete restrict,
  title         text not null check (length(trim(title)) > 0),
  description   text not null,
  listing_type  text not null check (listing_type in ('sale', 'rent')),
  property_type text not null check (property_type in ('apartment', 'duplex', 'bungalow', 'terrace', 'land')),
  status        text not null default 'active' check (status in ('active', 'under_offer', 'sold', 'let')),
  -- Money is an integer in minor units (kobo), never a float. The upper bound keeps it inside
  -- JavaScript's safe-integer range so the API can return it as a JSON number without losing precision.
  price_minor   bigint not null check (price_minor between 1 and 9007199254740991),
  currency      char(3) not null default 'NGN' check (currency ~ '^[A-Z]{3}$'),
  bedrooms      integer not null check (bedrooms >= 0),
  bathrooms     integer not null check (bathrooms >= 0),
  address       text not null,
  city          text not null,
  state         text not null,
  listed_at     timestamptz not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table viewings (
  id              uuid primary key default gen_random_uuid(),
  listing_id      uuid not null references listings(id) on delete restrict,
  requester_name  text not null check (length(trim(requester_name)) > 0),
  requester_email text not null,
  scheduled_for   timestamptz not null,
  status          text not null default 'requested' check (status in ('requested', 'confirmed', 'cancelled', 'completed')),
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- A listing cannot be double-booked: at most one live (non-cancelled) viewing per time slot.
create unique index viewings_one_live_booking_per_slot
  on viewings (listing_id, scheduled_for)
  where status <> 'cancelled';

create trigger agencies_updated_at before update on agencies for each row execute function set_updated_at();
create trigger agents_updated_at   before update on agents   for each row execute function set_updated_at();
create trigger listings_updated_at before update on listings for each row execute function set_updated_at();
create trigger viewings_updated_at before update on viewings for each row execute function set_updated_at();

-- Indexes. Cursor pagination orders by (sort column, id), so each sortable column is indexed
-- together with id; foreign keys are indexed because the nested endpoints filter on them.
create index agencies_name_id         on agencies (name, id);
create index agencies_founded_year_id on agencies (founded_year, id);
create index agencies_created_at_id   on agencies (created_at, id);
create index agencies_city            on agencies (city);

create index agents_agency_id           on agents (agency_id);
create index agents_full_name_id        on agents (full_name, id);
create index agents_years_experience_id on agents (years_experience, id);
create index agents_created_at_id       on agents (created_at, id);

create index listings_agent_id      on listings (agent_id);
create index listings_listed_at_id  on listings (listed_at, id);
create index listings_price_id      on listings (price_minor, id);
create index listings_bedrooms_id   on listings (bedrooms, id);
create index listings_city_type     on listings (city, listing_type);

create index viewings_listing_id on viewings (listing_id);
